### ISSUE TITLE
Will the for loop structure slow down?

### ISSUE THREAD

**Issue by huimxu** [sxpro/HetConvolution2d_pytorch#1]
hi,
I found some for loop structure in your code, Will the for loop structure slow down the execution speed?

Is there any other methods for hetconv?

**Comment by sxpro** [comment]
At present, I don't know how to do except modify the underlying code... I'll try.

**Comment by sxpro** [comment]
> hi,
> I found some for loop structure in your code, Will the for loop structure slow down the execution speed?
> 
> Is there any other methods for hetconv?

Efficient-hetconv2d of Hetconv.py  I refer to the work of others and modify it.
