### ISSUE TITLE
experiment?

### ISSUE THREAD

**Issue by miaoshuyu** [sxpro/HetConvolution2d_pytorch#2]
Thanks for your code! have you done experiments on public datasets? What is the result of accuracy and speed?

**Comment by sxpro** [comment]
> Thanks for your code! have you done experiments on public datasets? What is the result of accuracy and speed?

I haven't do these experiments... I should write Hetconv by CUDA, which will have a good speed.

**Comment by sxpro** [comment]
> Thanks for your code! have you done experiments on public datasets? What is the result of accuracy and speed?

You can use Efficient-Hetconv2d of Hetconv.py to do  experiments on public datasets
