### ISSUE TITLE
Efficient HetConv Implementation

### ISSUE THREAD

**Issue by irvinxav** [sxpro/HetConvolution2d_pytorch#3]
I think loop in this code will slow down the convolution operation. Alternatively, you can do the same operation by dividing input feature maps into two groups. On one input feature maps group you can apply 1x1 convolution, and on second input feature maps group you can use for 3x3 convolution parallelly,  then finally summing the results.

 for example, HetConv with part p=4, do the following:

Divide input feature maps into four equal parts (p1, p2, p3, and p4)  along channel wise. Now HetConv have only  four variations shown below:

1. 3x3p1 + 1x1p2 + 1x1p3 + 1x1p4 = apply 3x3 on p1 and apply 1x1 on concatenate(p2,p3,p4) then sum the results. Total such filters will be C_out/parts or C_out/4. 

2. 1x1p1 + 3x3p2 + 1x1p3 + 1x1p4 = apply 3x3 on p2 and apply 1x1 on concatenate(p1,p3,p4) then sum the results. Total such filters will be C_out/parts or C_out/4. 

3. 1x1p1 + 1x1p2 + 3x3p3 + 1x1p4 = apply 3x3 on p3 and apply 1x1 on concatenate(p1,p2,p4) then sum the results. Total such filters will be C_out/parts or C_out/4. 

4. 1x1p1 + 1x1p2 + 1x1p3 + 3x3p4 = apply 3x3 on p4 and apply 1x1 on concatenate(p1,p2,p3) then sum the results. Total such filters will be C_out/parts or C_out/4.

**Comment by sxpro** [comment]
> I think loop in this code will slow down the convolution operation. Alternatively, you can do the same operation by dividing input feature maps into two groups. On one input feature maps group you can apply 1x1 convolution, and on second input feature maps group you can use for 3x3 convolution parallelly, then finally summing the results.
> 
> for example, HetConv with part p=4, do the following:
> 
> Divide input feature maps into four equal parts (p1, p2, p3, and p4) along channel wise. Now HetConv have only four variations shown below:
> 
> 1. 3x3p1 + 1x1p2 + 1x1p3 + 1x1p4 = apply 3x3 on p1 and apply 1x1 on concatenate(p2,p3,p4) then sum the results. Total such filters will be C_out/parts or C_out/4.
> 2. 1x1p1 + 3x3p2 + 1x1p3 + 1x1p4 = apply 3x3 on p2 and apply 1x1 on concatenate(p1,p3,p4) then sum the results. Total such filters will be C_out/parts or C_out/4.
> 3. 1x1p1 + 1x1p2 + 3x3p3 + 1x1p4 = apply 3x3 on p3 and apply 1x1 on concatenate(p1,p2,p4) then sum the results. Total such filters will be C_out/parts or C_out/4.
> 4. 1x1p1 + 1x1p2 + 1x1p3 + 3x3p4 = apply 3x3 on p4 and apply 1x1 on concatenate(p1,p2,p3) then sum the results. Total such filters will be C_out/parts or C_out/4.

hahahaha, I finished it yesterday by this way. Thanks!

**Comment by Flames60** [comment]
Hi @sxpro , I have a question that if you set the output channels to 1 in line 49 and 50:
`layers.append(nn.Conv2d(self.in_feats//p, 1, 3, 1, 1, groups=self.in_feats//p))`
then you can save the sum operation in line 71 like this:
`out_ = out1x1 + out3x3`
is it?

**Comment by sxpro** [comment]
> Hi @sxpro , I have a question that if you set the output channels to 1 in line 49 and 50:
> `layers.append(nn.Conv2d(self.in_feats//p, 1, 3, 1, 1, groups=self.in_feats//p))`
> then you can save the sum operation in line 71 like this:
> `out_ = out1x1 + out3x3`
> is it?

Great! But groups=1, hahaha

**Comment by irvinxav** [comment]
I have implemented efficient HetConv 
https://github.com/irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions

**Comment by sxpro** [comment]
> I have implemented efficient HetConv
> https://github.com/irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions

I think your program seems to be incorrect. I will take a closer look in a few days.

**Comment by sxpro** [comment]
> I have implemented efficient HetConv
> https://github.com/irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions

I seem to understand it.
