### ISSUE TITLE
what is the meaning of switching the sequence of 3x3 conv?>

### ISSUE THREAD

**Issue by Flames60** [sxpro/HetConvolution2d_pytorch#4]
![image](https://user-images.githubusercontent.com/18513712/56782363-689b7380-6819-11e9-8d4b-32eedd444631.png)
Hi~
As shown above, the 3x3 conv changes its place on every output channel, what is the meaning of this do you think?

**Comment by irvinxav** [comment]
I think by this way we can ensure that for every channel there will be some (equal to C_out/part) 3X3 kernel associated with them, but if you look at figure carefully then there will be  part (say 4 if part=4) number of distinct pattern and each pattern will be repeating exactly C_out/part times.

**Comment by Flames60** [comment]
> I think by this way we can ensure that for every channel there will be some (equal to C_out/part) 3X3 kernel associated with them, but if you look at figure carefully then there will be part (say 4 if part=4) number of distinct pattern and each pattern will be repeating exactly C_out/part times.

Thanks for your reply, it makes sense.
