### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Flames60** [sxpro/HetConvolution2d_pytorch#5]
I tried HetConv on resnet18, and I got this error after the layer1. When I changed the batchsize to half, I got this errot again after the layer2.
How to solve it?
Thanks!
`               out1x1 = torch.cat((out1x1, x[:, j:j + 1, :, :]), 1)`
`RuntimeError: CUDA error: out of memory`

**Comment by Flames60** [comment]
I have tried deleting the var out1x1 and out3x3 like this:
`           out.append(out_)`
`            del out_, out3x3, out1x1`
`            gc.collect()
`
But it does not work.

**Comment by sxpro** [comment]
Maybe you should tune a smaller batch_size
Efficiency is a big problem, the hetconv  writen by CUDA will have a good efficiency. I 'm learning how to use CUDA...

**Comment by irvinxav** [comment]
I have implemented Memory efficient HetConv
https://github.com/irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions

**Comment by sxpro** [comment]
> Maybe you should tune a smaller batch_size
> Efficiency is a big problem, the hetconv writen by CUDA will have a good efficiency. I 'm learning how to use CUDA...

Now, you can use Efficient_hetconv2d of Hetconv.py

**Comment by sxpro** [comment]
> I have tried deleting the var out1x1 and out3x3 like this:
> ` out.append(out_)`
> ` del out_, out3x3, out1x1`
> ` gc.collect()`
> But it does not work.

They increase the depth or width of the network to compensate for the loss caused by the use of recursive networks. These points enable the model to preserve the details of the image as it is reconstructed, but at the cost of increased number of operations and time of inference.

**Comment by sxpro** [comment]
> I have tried deleting the var out1x1 and out3x3 like this:
> ` out.append(out_)`
> ` del out_, out3x3, out1x1`
> ` gc.collect()`
> But it does not work.

Now you can use Efficient_hetconv2d of Hetconv.py
