### ISSUE TITLE
Error in efficient implementation

### ISSUE THREAD

**Issue by d-li14** [sxpro/HetConvolution2d_pytorch#6]
@sxpro In each different output channel, the locations of 3x3 or 1x1 kernel are different and the weights are not shared, so I think it cannot be approximated with group convolution.

**Comment by sxpro** [comment]
> @sxpro In each different output channel, the locations of 3x3 or 1x1 kernel are different and the weights are not shared, so I think it cannot be approximated with group convolution.

That's right. Efficient_hetconv is different from the original hetconv, just designed for efficiency if it not runs on CUDA.

**Comment by d-li14** [comment]
As far as I am concerned, it is an absolutely different operation from the original HetConv, even significantly different from the layout in this [picture](https://github.com/irvinxav/Efficient-HetConv-Heterogeneous-Kernel-Based-Convolutions/blob/master/img/1.png).
Furthermore, `self.conv_1x1(x) - self.conv_1x1_(x)` will also not make sense due to different weights.

**Comment by sxpro** [comment]
You can refer to [https://github.com/zhang943/Approximate-HetConv/issues/1#issuecomment-486956551](url). Some channels use both 3x3 convolution and 1x1 convolution， so `self.conv_1x1(x) - self.conv_1x1_(x)` is as consistent as possible with the original hetconv.

**Comment by sxpro** [comment]
[this](https://github.com/zhang943/Approximate-HetConv/issues/1#issuecomment-486956551. )

**Comment by d-li14** [comment]
weights of conv_1x1 and conv_1x1_ are different in both shape and values, thus conv_1x1_ cannot cancel out the effect of conv_1x1 kernels in the locations of conv_3x3 kernels

**Comment by sxpro** [comment]
It is ok that conv_1x1_  and conv_3x3 can be in the same position

**Comment by d-li14** [comment]
> It is ok that conv_1x1_ and conv_3x3 can be in the same position

Sure, but it's not relevant to the concern
